---
title: "string practice"
author: "Marie Rivers"
date: "8/17/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Task 3: Practice with strings
```{r}
alarm_report <- data.frame(
  stringsAsFactors = FALSE,
              date = c("2020-03-14", "2020-03-15", "2020-04-10", "2020-04-18"),
          building = c("Engineering-North",
                       "Bren Hall","Engineering-South","Engr-North"),
     alarm_message = c("10:02am – HVAC system down, facilities management alerted",
                       "8:24am – Elevator North out of service",
                       "12:41am – Fire alarm, UCSB fire responded and cleared",
                       "9:58pm – Campus point emergency siren, UCPD responded")
)
```

```{r}
alarm_report <- alarm_report %>% 
  str_replace("Engr", "Engineer")
alarm_report

alarm_report <- alarm_report %>% 
  separate(building, into = c("building", "wing"), sep = " ")
```
alarm_report <- alarm_report %>% 
  separate(building, into = c(building, wing, sep = "-"))
